package io.mosip.certify.util;

import org.junit.jupiter.api.Test;

import static org.junit.jupiter.api.Assertions.*;

class PKCS12ReaderTest {

    @Test
    void testExtract() {
        KeyPairAndCertificate extract = new PKCS12Reader().extract("MIGHAgEAMBMGByqGSM49AgEGCCqGSM49AwEHBG0wawIBAQQgc/l+Y4UL5u42T8ugxSlUWjh1V+ZBJP1EAImDa1VJYvyhRANCAAQceevdAPMdDZ6mz7khfXP/db+ItLwqKSsUQWw8nSwUTQ6LSMtvnUxy/r7bCdjhj+AMnqYX8cOEickarfOSKuVq||LS0tLS1CRUdJTiBDRVJUSUZJQ0FURS0tLS0tCk1JSUIvVENDQWFNQ0ZFaG0vNVhaK1BsbHpYMWkwUTR4SkRjNStyUUtNQW9HQ0NxR1NNNDlCQU1DTUlHQU1Rc3cKQ1FZRFZRUUdFd0pKVGpFTE1Ba0dBMVVFQ0F3Q1MwRXhFakFRQmdOVkJBY01DVUpCVGtkQlRFOVNSVEVPTUF3RwpBMVVFQ2d3RlNVbEpWRUl4RERBS0JnTlZCQXNNQTBSRFV6RVFNQTRHQTFVRUF3d0hRMFZTVkVsR1dURWdNQjRHCkNTcUdTSWIzRFFFSkFSWVJiVzl6YVhCeFlVQm5iV0ZwYkM1amIyMHdIaGNOTWpReE1ERXdNRGN5TlRNd1doY04KTWpVeE1ERXdNRGN5TlRNd1dqQ0JnREVMTUFrR0ExVUVCaE1DU1U0eEN6QUpCZ05WQkFnTUFrdEJNUkl3RUFZRApWUVFIREFsQ1FVNUhRVXhQVWtVeERqQU1CZ05WQkFvTUJVbEpTVlJDTVF3d0NnWURWUVFMREFORVExTXhFREFPCkJnTlZCQU1NQjBORlVsUkpSbGt4SURBZUJna3Foa2lHOXcwQkNRRVdFVzF2YzJsd2NXRkFaMjFoYVd3dVkyOXQKTUZrd0V3WUhLb1pJemowQ0FRWUlLb1pJemowREFRY0RRZ0FFSEhucjNRRHpIUTJlcHMrNUlYMXovM1cvaUxTOApLaWtyRkVGc1BKMHNGRTBPaTBqTGI1MU1jdjYrMnduWTRZL2dESjZtRi9IRGhJbkpHcTN6a2lybGFqQUtCZ2dxCmhrak9QUVFEQWdOSUFEQkZBaUVBMUJTOW1jT2RJa2ZvYTF1RlU1REEyVjRFM3NtOHpZNjJKdk5GOWI3alRUb0MKSUNoSDVwWUhvWjlZWjJkZmNzdHdKSC9yQnBQZy9rcXJ5K0tDalJRd3UvdmMKLS0tLS1FTkQgQ0VSVElGSUNBVEUtLS0tLQo=");
        System.out.println("extract "+extract);
        KeyPairAndCertificate extract1 = new PKCS12Reader().extract("MIGHAgEAMBMGByqGSM49AgEGCCqGSM49AwEHBG0wawIBAQQgC2izjszCdnjunlll09LFGbx1IwxQ\n" +
                "IbjLZcItNYC+1rWhRANCAASoeI7VtTHj1Xv61KR1c1QqXprvE9jt6dOryg+emmR4Y91u6h0U80KW\n" +
                "dzyJsyIwxt+pm2JbafvAvayeSCnFfIZh||LS0tLS1CRUdJTiBDRVJUSUZJQ0FURS0tLS0tCk1JSUIvakNDQWFNQ0ZIRnIwNDBRVC9kK1ZKampv\n" +
                "bWc1VjF3VThMcFhNQW9HQ0NxR1NNNDlCQU1DTUlHQU1Rc3cKQ1FZRFZRUUdFd0pKVGpFTE1Ba0dB\n" +
                "MVVFQ0F3Q1MwRXhFakFRQmdOVkJBY01DVUpCVGtkQlRFOVNSVEVPTUF3RwpBMVVFQ2d3RlNVbEpW\n" +
                "RUl4RERBS0JnTlZCQXNNQTBSRFV6RVFNQTRHQTFVRUF3d0hRMFZTVkVsR1dURWdNQjRHCkNTcUdT\n" +
                "SWIzRFFFSkFSWVJiVzl6YVhCeFlVQm5iV0ZwYkM1amIyMHdIaGNOTWpReE1ERXdNRGN5TmpFNFdo\n" +
                "Y04KTWpVeE1ERXdNRGN5TmpFNFdqQ0JnREVMTUFrR0ExVUVCaE1DU1U0eEN6QUpCZ05WQkFnTUFr\n" +
                "dEJNUkl3RUFZRApWUVFIREFsQ1FVNUhRVXhQVWtVeERqQU1CZ05WQkFvTUJVbEpTVlJDTVF3d0Nn\n" +
                "WURWUVFMREFORVExTXhFREFPCkJnTlZCQU1NQjBORlVsUkpSbGt4SURBZUJna3Foa2lHOXcwQkNR\n" +
                "RVdFVzF2YzJsd2NXRkFaMjFoYVd3dVkyOXQKTUZrd0V3WUhLb1pJemowQ0FRWUlLb1pJemowREFR\n" +
                "Y0RRZ0FFcUhpTzFiVXg0OVY3K3RTa2RYTlVLbDZhN3hQWQo3ZW5UcThvUG5wcGtlR1BkYnVvZEZQ\n" +
                "TkNsbmM4aWJNaU1NYmZxWnRpVzJuN3dMMnNua2dweFh5R1lUQUtCZ2dxCmhrak9QUVFEQWdOSkFE\n" +
                "QkdBaUVBbDhNV0xlQndIdkdDbm0yd1VTNjh2YW84RCtVSDF1NkJ3MHR2NDV3VnlvMEMKSVFERDRQ\n" +
                "c05Vb2x4Z3JxMzVGWUJONUpRbStqN0lnZlBtZUZwRm02TUw0R3ZXQT09Ci0tLS0tRU5EIENFUlRJ\n" +
                "RklDQVRFLS0tLS0K");
        System.out.println("extract "+extract1);
    }
}
